server:
  port: 9010

spring:
  application:
    name: campus-user-auth-service
  profiles:
    active: local


mybatis-plus:
  configuration:
    map-underscore-to-camel-case: true
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  global-config:
    db-config:
      id-type: auto

campus:
  security:
    token-expire-seconds: 86400

knife4j:
  enable: true

springdoc:
  api-docs:
    enabled: true
  swagger-ui:
    enabled: true

logging:
  level:
    com.god.userauth: debug
